name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: past-due/fetch-release-info@master
        with:
          github_repo: 'nlohmann/json'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          calculate_asset_info: true
      - name: Archive output of run
        uses: actions/upload-artifact@v1
        with:
          name: releases
          path: releases
